name: Read file Manually

on: 
  workflow_dispatch:

jobs:
  read-file:
  runs-on:ubuntu-latest

  steps:
    name:Check Repoisitory
    uses:actions/checkout@v4

    -name:Read demo.txt file
    run:cat app.txt
